version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_poc
    environment:
      POSTGRES_DB: poc
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    pg_data: ~